// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB93d8vCuxGdAdR0kvu_J0gS7inFUQk5pg',
    appId: '1:252383466912:web:8758219d1b68913d5f00c5',
    messagingSenderId: '252383466912',
    projectId: 'appointapp-b9a66',
    authDomain: 'appointapp-b9a66.firebaseapp.com',
    databaseURL: 'https://appointapp-b9a66-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appointapp-b9a66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtO3hug0aXjVtSZVY69gILfiW4vNfg4SU',
    appId: '1:252383466912:android:4bd24855ef97aa715f00c5',
    messagingSenderId: '252383466912',
    projectId: 'appointapp-b9a66',
    databaseURL: 'https://appointapp-b9a66-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appointapp-b9a66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMUHWIr_QLAmP1zc3zqqS9kIHqkNwIsY',
    appId: '1:252383466912:ios:6c9a94b9eebcba1f5f00c5',
    messagingSenderId: '252383466912',
    projectId: 'appointapp-b9a66',
    databaseURL: 'https://appointapp-b9a66-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appointapp-b9a66.appspot.com',
    iosClientId: '252383466912-ft7qglbmf79lqidinf11r4qs23735icb.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointAppGit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMUHWIr_QLAmP1zc3zqqS9kIHqkNwIsY',
    appId: '1:252383466912:ios:6c9a94b9eebcba1f5f00c5',
    messagingSenderId: '252383466912',
    projectId: 'appointapp-b9a66',
    databaseURL: 'https://appointapp-b9a66-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appointapp-b9a66.appspot.com',
    iosClientId: '252383466912-ft7qglbmf79lqidinf11r4qs23735icb.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointAppGit',
  );
}
